// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PBXDashboard_Dev.Models;

namespace PBXDashboard.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210804134615_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PBXDashboard_Dev.Models.Call", b =>
                {
                    b.Property<long>("CallID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CdrCallID")
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FromAccountID")
                        .HasColumnType("int");

                    b.Property<string>("FromName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PBXID")
                        .HasColumnType("bigint");

                    b.Property<long?>("QueueID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TalkDuration")
                        .HasColumnType("int");

                    b.Property<string>("To")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToAccountID")
                        .HasColumnType("int");

                    b.Property<string>("ToNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("int");

                    b.Property<string>("UniqueID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CallID");

                    b.HasIndex("QueueID");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("PBXDashboard_Dev.Models.CurrentCall", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromCallerIdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromCallerIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PBXID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToCallerIdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToCallerIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CurrentCalls");
                });

            modelBuilder.Entity("PBXDashboard_Dev.Models.Event", b =>
                {
                    b.Property<long>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CallID")
                        .HasColumnType("bigint");

                    b.Property<string>("Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventID");

                    b.HasIndex("CallID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("PBXDashboard_Dev.Models.Extension", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallQueueName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAdditionalPhones")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberCount")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("QueueID")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QueueID");

                    b.ToTable("Extensions");
                });

            modelBuilder.Entity("PBXDashboard_Dev.Models.Queue", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strategy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("PBXDashboard_Dev.Models.QueueLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CallID")
                        .HasColumnType("bigint");

                    b.Property<int>("EnterPosition")
                        .HasColumnType("int");

                    b.Property<string>("MemberAccountID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberMisses")
                        .HasColumnType("int");

                    b.Property<string>("MemberName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueAccountID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueueName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TalkTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WaitTime")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CallID");

                    b.ToTable("QueueLogs");
                });

            modelBuilder.Entity("PBXDashboard_Dev.Models.Report", b =>
                {
                    b.Property<long>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReportString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ReportID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("PBXDashboard_Dev.Models.TalkTimeRecord", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CallDuration")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("TalkingDuration")
                        .HasColumnType("int");

                    b.Property<int>("TotalCalls")
                        .HasColumnType("int");

                    b.Property<int>("TotalIncomingCalls")
                        .HasColumnType("int");

                    b.Property<int>("TotalOutgoingCalls")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("TalkTimeRecords");
                });

            modelBuilder.Entity("PBXDashboard_Dev.Models.Call", b =>
                {
                    b.HasOne("PBXDashboard_Dev.Models.Queue", null)
                        .WithMany("WaiteringCalls")
                        .HasForeignKey("QueueID");
                });

            modelBuilder.Entity("PBXDashboard_Dev.Models.Event", b =>
                {
                    b.HasOne("PBXDashboard_Dev.Models.Call", "Call")
                        .WithMany("Events")
                        .HasForeignKey("CallID");
                });

            modelBuilder.Entity("PBXDashboard_Dev.Models.Extension", b =>
                {
                    b.HasOne("PBXDashboard_Dev.Models.Queue", null)
                        .WithMany("Members")
                        .HasForeignKey("QueueID");
                });

            modelBuilder.Entity("PBXDashboard_Dev.Models.QueueLog", b =>
                {
                    b.HasOne("PBXDashboard_Dev.Models.Call", null)
                        .WithMany("QueueLogs")
                        .HasForeignKey("CallID");
                });
#pragma warning restore 612, 618
        }
    }
}
