import { Call } from "./call.model";

export class Extension {
  constructor(
    public number?: string,
    public status?: string,
    public subStatus?: string,
    public dateCreated?: Date,
    public lastName?: string,
    public display?: string,
    public hasAdditionalPhones?: boolean,
    public typeDisplay?: string,
    public accountID?: string,
    public firstName?: string,
    public memberCount?: number,
    public strategy?: string,
    public type?: string,
    public lastCall?: Call,
    public lastEvent?: Event,
    public isActive?: boolean,
    public coolDownTime?: Date,
    public totalAnswersList?: number[],
    public percentAnswersList?: string[],
    public idleTime?: string,
    public talkTime?: string,
    public callTime?: string,
    public extensionClass?: string,
    public activeTime?: string,
    public lastActivity?: string,
    public averageIdleTime?: string,
    public iCalls?: number,
    public oCalls?: number,
    public tCalls?: number,
    public averageCallTime?: string,
    public glyphiconClass?: string,
    public loggedInTime?: string,
    public idleClass?: string,
    public activeIClass?: string,
    public statusList?: string[],
    public subStatusList?: string[],
    public durationList?: number[],
    public logoutTimesList?: Date[],
    public logoutTimesStringList?: string[],
    public breakTotal?: number,
    public breakTypeList?: string[],
    public breakTypeTotals?: number[],
    public breakTypeNumber?: number[],
    public loginTimesList?: string[],
  ) { }
}
